# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sub_View.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Data import Data_sorting

class sub_window(object):

    def __init__(self, product, device, lpcode):
        self.product = product
        self.device = device
        self.lpcode = lpcode

    def setupUi(self, subwindow):
        subwindow.setObjectName("Subwindow")
        subwindow.resize(650, 329)

        self.centralwidget = QtWidgets.QWidget(subwindow)
        self.centralwidget.setObjectName("centralwidget")

        self.listwidget = QtWidgets.QListWidget(self.centralwidget)
        self.listwidget.setGeometry(QtCore.QRect(10, 40, 130, 230))
        self.listwidget.setObjectName("listWidget")

        for i in range(len(Data_sorting(self.product, self.device, self.lpcode).lp_list())):
            self.itemlist = QtWidgets.QListWidgetItem()
            self.itemlist.setText(str(Data_sorting(self.product, self.device, self.lpcode).lp_list().iloc[i][0]))
            self.listwidget.insertItem(i, self.itemlist)
            self.itemlist.setTextAlignment(QtCore.Qt.AlignCenter)

        # 태그값 테이블
        self.tag_table = QtWidgets.QTableWidget(self.centralwidget)
        self.tag_table.setGeometry(QtCore.QRect(430, 40, 200, 230))
        self.tag_table.setObjectName("font_table")

        # 이미지 뷰 영역
        self.graphicsView = QtWidgets.QLabel(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(150, 40, 260, 230))
        self.graphicsView.setText('LP 이미지 영역')
        self.graphicsView.setObjectName("graphicsView")

        #LP 코드목록
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 80, 20))
        self.label_2.setObjectName("label_2")

        # 이미지 뷰어 라벨
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(430, 10, 80, 20))
        self.label_3.setObjectName("label_3")

        # 태그값 라벨
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 10, 80, 20))
        self.label_4.setObjectName("label_4")

        subwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(subwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 591, 21))
        self.menubar.setObjectName("menubar")

        subwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(subwindow)
        self.statusbar.setObjectName("statusbar")
        subwindow.setStatusBar(self.statusbar)

        self.retranslateUi(subwindow)
        QtCore.QMetaObject.connectSlotsByName(subwindow)

        #클릭 이벤트
        self.listwidget.clicked.connect(self.tag_event)
        self.listwidget.clicked.connect(self.click_event)

    # 클릭 이벤트 생성
    def tag_event(self):
        a = self.listwidget.currentItem().text()
        code_name = Data_sorting(self.product, self.device, self.lpcode).lp_tag(a)

        self.tag_table.setRowCount(len(code_name.index))
        self.tag_table.setColumnCount(len(code_name.columns))
        self.tag_table.setHorizontalHeaderLabels(list(code_name.columns))

        for i in range(len(code_name)):
            for j in enumerate(code_name.iloc[i]):
                self.tag_table.setItem(i, j[0], QtWidgets.QTableWidgetItem(str(j[1])))

        self.tag_table.resizeColumnsToContents()
        self.tag_table.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)

    # LP 이미지 연결
    def click_event(self):
        name = './LP/'+ self.product + "/" + self.listwidget.currentItem().text()
        pixmap = QtGui.QPixmap(name)
        self.graphicsView.setPixmap(pixmap)
        self.graphicsView.setScaledContents(True)

    def retranslateUi(self, subwindow):
        _translate = QtCore.QCoreApplication.translate
        subwindow.setWindowTitle(_translate("subwindow", "Subwindow"))
        self.graphicsView.setText(_translate("subwindow", "TextLabel"))
        self.label_2.setText(_translate("subwindow", "# LP List"))
        self.label_3.setText(_translate("subwindow", "# 태그값"))
        self.label_4.setText(_translate("subwindow", "# LP 이미지"))
